Improve error message for invalid input file

diff --git a/esh b/esh
--- a/esh
+++ b/esh
@@ -278,6 +278,9 @@ fi
 
 INPUT="$1"; shift
 [ "$INPUT" != '-' ] || INPUT=''
+if [ "$INPUT" ] && ! [ -f "$INPUT" -a -r "$INPUT" ]; then
+	echo "$PROGNAME: can't read $INPUT: not a file or not readable" >&2; exit 10
+fi
 
 # Validate arguments.
 for arg in "$@"; do
